language: node_js
node_js:
  - "6"
  - "5"
services:
  - postgresql
script: npm run cover
before_script:
  - psql -c 'create database tape_test;' -U postgres
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
